trigger:
- none  # Manual or scheduled runs only

resources:
  repositories:
    - repository: iac
      type: git
      name: yourproject/iac-terraform
      ref: main

pool:
  vmImage: ubuntu-latest

variables:
  ENV: dev1
  STACK: vpc  # 👈 Change this to your stack name
  FAB_STACKS_PATH: $(Pipeline.Workspace)/iac/stacks

steps:
- checkout: self
  displayName: "Checkout Infra Orchestrator Repo"

- checkout: iac
  displayName: "Checkout IaC (Terraform) Repo"

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    pip install poetry
    poetry install
  displayName: "Install Fabric dependencies"

- script: |
    poetry run fab sync_tfvars:$(ENV)
    poetry run fab upload_artifacts:$(ENV)
    poetry run fab plan_stack:$(ENV),$(STACK)
    poetry run fab apply_stack:$(ENV),$(STACK)
  displayName: "Run Terraform stack orchestration"
  env:
    FAB_STACKS_PATH: $(FAB_STACKS_PATH)
